package com.patricktwohig.jobber.cli;

public enum ExitCode {
    SUCCESS,
    UNSUPPORTED_INPUT_FORMAT,
    UNSUPPORTED_OUTPUT_FORMAT,
    INVALID_URL_FORMAT,
    IO_EXCEPTION,
    INVALID_PARAMETER,
    INVALID_OUTPUT_DESTINATION
}
